// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1-2PCCm1AoKe4JI6CNVMSN9ZypIE5JQE',
    appId: '1:942523332292:web:a24c48b3508def7e8c7b91',
    messagingSenderId: '942523332292',
    projectId: 'fooddelivery-6bd18',
    authDomain: 'fooddelivery-6bd18.firebaseapp.com',
    storageBucket: 'fooddelivery-6bd18.firebasestorage.app',
    measurementId: 'G-C9EWFV3VSG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2DycpcKHEQk_-OZKHnXGfPI8jqf-cmVM',
    appId: '1:942523332292:ios:fef86f7c3fccbe388c7b91',
    messagingSenderId: '942523332292',
    projectId: 'fooddelivery-6bd18',
    storageBucket: 'fooddelivery-6bd18.firebasestorage.app',
    iosBundleId: 'com.example.foodCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2DycpcKHEQk_-OZKHnXGfPI8jqf-cmVM',
    appId: '1:942523332292:ios:fef86f7c3fccbe388c7b91',
    messagingSenderId: '942523332292',
    projectId: 'fooddelivery-6bd18',
    storageBucket: 'fooddelivery-6bd18.firebasestorage.app',
    iosBundleId: 'com.example.foodCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1-2PCCm1AoKe4JI6CNVMSN9ZypIE5JQE',
    appId: '1:942523332292:web:d9b025056b3359ba8c7b91',
    messagingSenderId: '942523332292',
    projectId: 'fooddelivery-6bd18',
    authDomain: 'fooddelivery-6bd18.firebaseapp.com',
    storageBucket: 'fooddelivery-6bd18.firebasestorage.app',
    measurementId: 'G-42B1JD299F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUjsQk7fDiJPlF9UIRR-zjy1EciI89NE0',
    appId: '1:942523332292:android:ef64e4f59ff7b9718c7b91',
    messagingSenderId: '942523332292',
    projectId: 'fooddelivery-6bd18',
    storageBucket: 'fooddelivery-6bd18.firebasestorage.app',
  );

}